sudo: required

language: go

services:
  - docker

go:
  - 1.7rc3

matrix:
  allow_failures:
    - go: tip

branches:
  only:
    - master
    - travis-testing

# Having an install function stops Travis from trying to do automagic things
# with godep
install:
  - true

script:
  - make test testrace
